apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  labels:
    app: echo-server
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
      version: v1
  template:
    metadata:
      labels:
        app: echo-server
        version: v1
    spec:
      containers:
      - name: echo-server
        image: taylorshaulis/k8s-netgen-echo-server:latest
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  labels:
    app: echo-server
    service: echo-server
    version: v1
spec:
  selector:
    app: echo-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: listenport